### ISSUE TITLE
symlink.xml file missing

### ISSUE THREAD

**Issue by logicminds** [digglife/puppet-sep#1]
Hey, I think you forgot to add the symlink.xml file in the files directory?  Are you able to add this?

**Comment by digglife** [comment]
@logicminds Actutally it's on purpose.The symlink.xml is supposed to be exported from internal SEPM server. The information in it is specifically for my company, so I didn't add it to the repo.

**Comment by logicminds** [comment]
Could we templatize this file and also create parameters so that we don't have to export it, and then it won't contain any site specific data.  Are you able to send a gist with your site specific data removed?

**Comment by digglife** [comment]
@logicminds symlink.xml added. The tricky part is the `Kcs` in the `AgentCommunicationSetting` and the encoded certificate data. I guess the certificate data is not a problem, but I'm not sure if we can get the `Kcs` code without exporting the xml.

**Comment by logicminds** [comment]
@digglife I have already refactored this if your interested.  Its not complete as I need to gather a few pieces of information before completing everything.

https://gitlab.com/singlestone/puppet-sep/blob/refactor

**Comment by digglife** [comment]
:+1: Looks cool!
